# Generated by Django 4.2.3 on 2023-08-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='gambar_profil',
        ),
    ]
