# Generated by Django 4.2.3 on 2023-08-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profil_gambar_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='no_wa',
            field=models.CharField(default='00000', max_length=100, null=True),
        ),
    ]
