# Generated by Django 4.2.3 on 2023-08-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profil_no_wa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='imageProfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
