# Generated by Django 4.2.3 on 2023-08-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_subtotal_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
