# Generated by Django 4.2.3 on 2023-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_to_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='to_sms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
